
# Introduction
Unauthorized downloading of copyrighted works is a common and well-known phenomenon in today's Internet society. The broad downloading of different type of goods started at the end of the 20th century, but the sudden growth of Internet led to its everyday usage. Today software, songs, films, books and nearly anything what exists online can be downloaded from different sites. 

While the piracy of software, music and films are relatively well-studied ( @gopal2004behavioral, @rodman2006music, @koklic2014three), the research regarding (scientific-)book downloading is quite scarce. In this thesis, my aim is to look at the driving forces and behavior behind downloading books illegally from a Russian shadow-library, Library Genesis, especially analyzing the behavior of University students. I distinguish university students by only analyzing books that have rent prices. These books are textbooks used by university students, as rent price is only available for textbooks.
The analysis is different from other paper's approach, as it is based on observed data from downloads and not survey data. 

I use a rich dataset, with more than 1 million downloaded books for a time span of 5 and a half months. This allows me to get robust results and to draw conclusions about the real users of these websites. I believe this area is really interesting and should be understood more deeply, as the explanation behind why students are downloading textbook is not clear. It also poses heavy copyright issues and publishers realize significant losses due to piracy. On the other hand, some argue, that knowledge should be free and scientific papers or books should be made available free of charge [^1].

[^1]: https://archive.org/stream/GuerillaOpenAccessManifesto/Goamjuly2008_djvu.txt Guerilla Open Access Manifesto, Aaron Swartz.

In this thesis, I am looking at a specified part of the book industry: scientific books and textbooks, for which the demand is the highest among University students. I have chosen this subtopic because as a current Master's student, I would like to analyze my fellow students. Downloading from file sharing sites is a common thing among students, as one of their primary source for knowledge are the expensive textbooks. Students are really sensitive for prices, as the cost of University is high without the books as well (@heller1997student). Moreover, students have the free time and willingness to find these sites and often all of heir sources of entertainment, series, films or music are downloaded illegally.

With the help of this thesis, I can give insights to the driving forces of graduate downloaders and shed light on different interesting questions. I will first take a look at the descriptive statistics of the data and check, if there are any discrepancies in it. After that, I will use OLS regressions and correlations to see if the price has an effect on the number of downloads. After analyzing the prices, I will use a hurdle regression, to see how macro variables or the topic of the book effects the number of downloads. 

The thesis have two main questions: First, whether the price of a book has an effect on the number of downloads. Second, I investigate if a difference can be seen between different countries based on their region, GDP or growth. 

The setup of the thesis follows like this: In Part 2 I will describe how piracy is defined, take a short look at its history and summarize some findings from recent papers in the topic of illegal Internet downloading. In Part 3 I will describe the available dataset and the website it was acquired from, present the data's possible shortcomings and differences from previously used datasets. I present basic exploratory data analysis to have a good overview of the dataset. In Part 4 I have a look at some control OLS and hurdle regressions, trying to understand the possible explanation behind downloading. Part 5 discusses the thesis and gives recommendations for further development. 

# Literature review

## Piracy

Piracy is a part of human societies since the origins of civilization (@johns2010piracy) as people were copying intellectual content from other's without their permission. The meaning of piracy is still controversial in academic research. For this reason, there is no date in the past, for what scholars agree as the start of piracy. 

There are few definitions of piracy circulating in the academic field, but according to @karaganis2011media, piracy is "ubiquitous, increasingly
digital practices of copying that fall outside the boundaries of
copyright law". We can see that piracy is an illegal act, where somebody copies or steals an intellectual property of somebody else. 

People can have three driving forces to pirate content. First, it is a utility maximizing behavior, as the price of the pirated content is zero and the probability of getting caught is very small. Thus people have no fear of the consequences of downloading and avoid paying a price for copyrighted content.
The second, is the commercial war, where people make money from making pirate content available. They exploit the weakness of the system (too high price, too little supply).
The third one is when countries do not enforce the law, and let the piracy flourish. A good example for this is China, where counterfeited phones or books without copyrights exist nationwide, despite the laws of the Chinese government. This behavior helps them catch up to more developed countries.

These three forces can be interpreted as a development vehicle on individual, company and nation-wide level, respectively. In this thesis, I am analyzing both the individual and nation-wide level. 

## Piracy of books

The start of book trading gave birth to copyright and developed concepts relevant today as well. 
The piracy of the books started with Gutenberg's revolution (@johns2010piracy), as people were able to copy books within a reasonable time, without the author's permission - most of the time, without the knowledge of the original writer. During the (Pre-)Modern Era, the copyrights of the books were only valid for a city or a little area and other printers could freely print books from other cities. The owners of the copyright's of these books realised this issue, and started to establish connections through cities and ask help from their state to protect their rights. This co-operation lead to the exclusive right to print and sell books, limited in time, space and scope.

One institution enforcing these copyrights was "The Stationers' register" in London, which contained printing right of books' (today a patent register has the same aim). 
This process was close to law and politics in an era, when people were trying to get independent from the government, the topic became a well-known one in the whole society. Also, for authors and readers, this system was not beneficiary and pirated books started to circulate in the book shops. 

Pirated texts in this time were not only competitors on their own market (@balazs2011coda), but foreign printed copies entered other markets as well. Pirates were always there to exploit the shortcomings of the law and provide a cheaper, yet legal way to fulfill the demand for books. Moreover, small publishers started to surface who were really effective on the market: they were selling these books for a lower price, not taking the regulations of the government into account and believed in mass-printing: profiting little on one book, but selling lots of books.

A law-battle with the English monarch, led by a writer named Richard Atkyns (@johns1998nature) led later to the shutting down of the absolutistic book market and a more democratic came into its place, redefining piracy. The heart of this revolution was London, but it quickly span across Western Europe and led to a more free market. 
Up until 1886, there was no inter-country agreement on copyright, when the Berne Convention[^2] was signed (@balazs2011coda).

[^2]: http://www.wipo.int/treaties/en/text.jsp?file_id=283698

### The Russian way and the birth of LibGen

From this point on, pirates had a harder task to distribute their copies, however in some countries i.e. Russia, this treaty was not in effect, so piracy was more alive there than ever before. The demand for books was skyrocketing in The Soviet Union, because this was the primary tool for entertainment. On the other hand, the Soviet regime applied a very strict censorship which lead to a shortage of available books. As the USSR had not entered any treaties, people were also "free" to distribute translations of books - however, these were mainly released into the shadow market, as the censorship banned these books. With the advance of technology, other methods entered the pirates' tools, such as Xerox machines and CD-ROMs .

As the Internet started to establish itself, these shadow libraries, floating around on CDs were uploaded and gathered into online databases, where everyone was available to download them. One of the biggest site storing these books was Gigapedia, later called library.nu. This sites' aim was to gather all the offline, but digitally available books and organize them into a giant, online library. Library.nu closed down after a successful injuction by several publishers, however its library was merged into another page, Library Genesis, also known as LibGen. LibGen's catalogue is mirrored to more sites, who can easily add their own collection to the existing one. The mission of the site is to: 

* collect valuable academic literature
* build and maintain a community, who helps the inflow of the books and who can improve the quality of the uploaded documents
* make this service available for free.

LibGen's collection was Russian by default, but after the merge of library.nu, English books became dominant. (@bodo2014short)

## Piracy of software, music, films and books

Piracy on the Internet started in the 90's with illegal downloading of software. In that era, the prices of software were high, but a lot of people wanted to use them - for free. Christensen and Eining (@christensen1991factors) in an early study, asked university students about their knowledge about piracy laws. They found, that the majority of the students were using pirated content, even though they were aware of the laws. They stated, that they don't think, that the law would be enforced against them. @givon1995software also investigated the software piracy, but with an other approach. They used a diffusion model to track the transition from pirated content to legal copies. Although they found, that over 90% of the users utilized illegal software, they generated more than 80% of the profit of new software. They argued, that software piracy is not necessarily bad, as the shadow diffusion created the base of the customers.

The next industry where piracy became relevant was music. @bhattacharjee2003digital call illegal music downloading as the 2.0 of software piracy. The authors in this study also used a survey to look at downloaders attitude towards online music downloading. They found that price and bandwidth had a significant effect on the choice to utilize piracy. They also suggest, that the well-known music has more downloads. Today, with  the presence of Spotify or Tidal it is also interesting to see, how they suggested that music providers should switch to subscription based services, as the respondents were positive about that. 
In a more recent study, @podoshen2008take explores the relation of numerous effects to student's download decision. Podoshen also chose the survey approach, where he found, that avoiding payment is one of the key factors that students are downloading music. The survey data also revealed, that students were not afraid of the consequences of downloading, just like in the case of Christensen's paper. 

The third big industry affected by piracy was the film industry. As films are bigger files compared to songs, the introduction of online movie piracy only came with the upcoming of peer-to-peer (P2P) networks (@danaher2012reel). In his paper @fetscherin2005movie introduces a model, which shows, why do people choose to download films. The model gives evidence, that people download because of the low probability of being caught, while the users can reach very high quality products. Fetscherin also shows, that the perceived value of the films play an important role when people decide on downloading. In their paper, @bodo2012piracymovie investigate the case of Hungary with movie downloads. They take a different approach and track the traffic of three P2P networks. They found, that the biggest shaping factor of download choices is the failure of the markets to supply the demand. According to them , people download films because they do not find enough movies in traditional channels and this way they are forced to download.

The fourth industry where pirates became a real concern were books. @hoorebeek2003ebooks shows, that the option to download books has been available since the early 2000’s. Scanned versions were circulating on the web, on sites nearly identical to Napster. However, @rohde2001creation argues that the market for e-readers was not well established in that time and thus book downloading had no significant effect on the industry. The uprising of e-book piracy, came with the new versions of handheld devices (Kindle, and later tablets) capable of displaying books in a user-friendly format. 

Also, e-book piracy became really important in the academic field (@zimerman2011books), as students create a continuous demand for textbooks and scholarly articles. In his paper, Zimerman provides evidence, that the e-book piracy in the field of academia is clearly because of the low availability of books and articles. 

## Textbook piracy

Textbooks are always wanted products by University students, as they are one of the primary sources of knowledge. Also, after the education boom after the II. World War, in developed countries, like Western Europe and USA, a significantly bigger upturn in education started, with countries from Asia and Eastern Europe. 

Several websites or groups across the world were formed to transfer second-hand textbooks. The response for this from the bookmakers is the constant updating of the books - they make a new version every year, so students are forced to always buy the new ones. With the emerge of e-readers, the downloading of textbooks became more popular. 

@rebelo2015understanding was looking at this effect in a recent paper, where she looked at survey data from a Portuguese University and found, that the price of the book does not play a significant role, whether a book will be downloaded or not. In the study, she also found, that the downloading of the book is connected to the perceived usefulness of a book - books, that are considered to be more useful, are less likely to be downloaded. 

Another study, by @scorcu2012economic also researches the illegally obtained books. They concentrate on the individual and social characteristics of downloaders through a survey conducted in Italy and find that males are more likely to download books. Also, they suggest, that income or additional costs of living, such as travel expenses have an effect on the decision towards downloading a book. 

My thesis builds upon the above described literature and use real-life data to check, whether people really behave how they report it in surveys. It is interesting to pinpoint, that in the earlier literature about piracy, the authors described price as a significant factor that affects people’s behavior, while in the recent ones, the contents unavailability and low supply is shown as a significant one.
In the next part of the thesis I describe the dataset and the additional resources I am using and test if price has an effect on the number of downloads.

